week5/w5d1/dreams_app/config/routes.rb
Rails.application.routes.draw do
  root to: "users#new"
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :dreams
  resources :comments, only: [:create]
end

week5/w5d1/dreams_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :author_id, :commentable_id, :commentable_type, presence: true
  validates :spooky, inclusion: { in: [true, false] }

  belongs_to :commentable, polymorphic: true
end

week5/w5d1/dreams_app/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end

end

week5/w5d1/dreams_app/app/models/dream.rb
class Dream < ActiveRecord::Base
  validates :title, :content, :user_id, :completeness, presence: true
  validates :spooky, inclusion: { in: [true, false] }
  validates :completeness, inclusion: { in: (0..100) }

  belongs_to :user
  include Commentable
end

week5/w5d1/dreams_app/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :dreams
  include Commentable

  def self.generate_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
  end

  def reset_session_token!
    token = User.generate_token
    token = User.generate_token while User.exists?(session_token: token)
    self.session_token = token
    save!
    token
  end

  def ensure_session_token
    self.session_token ||= User.generate_token
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

week5/w5d1/dreams_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    # return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
    # @current_user = user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

week5/w5d1/dreams_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to :back
    else
      flash[:errors] = 'AHHH'
      redirect_to :back
    end
  end

  def comment_params
    params.require(:comment).permit(:body, :spooky, :commentable_type, :commentable_id)
  end
end

week5/w5d1/dreams_app/app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user_id = current_user.id
    if @dream.save
      redirect_to dream_url(@dream)
    else
      flash.now[:errors] = ['!NIGHTMARE!']
      render :new
    end
  end

  def index
    @dreams = Dream.includes(:user).all
  end

  def edit
    @dream = Dream.find(params[:id])
  end

  def update
    @dream = Dream.find(params[:id])
    if @dream.update(dream_params)
      redirect_to dream_url(@dream)
    else
      flash.now[:errors] = ['asdfadsfajdfkl;adsfjas;dkf']
      render :edit
    end
  end

  def show
    @dream = Dream.find(params[:id])
  end

  def dream_params
    params.require(:dream).permit(:title, :content, :completeness, :spooky)
  end
end

week5/w5d1/dreams_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login!(@user)
      redirect_to dreams_url
    else
      flash.now[:errors] = ['GIVE UP']
      render :new
    end
  end

  def destroy
    logout!
  end
end

week5/w5d1/dreams_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to dreams_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.includes(:dreams).find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

week5/w5d1/dreams_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    token = (<<-HTML)
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTML
    token.html_safe
  end
end

week5/w5d1/dreams_app/app/helpers/comments_helper.rb
module CommentsHelper
end

week5/w5d1/dreams_app/app/helpers/dreams_helper.rb
module DreamsHelper
end

week5/w5d1/dreams_app/app/views/dreams/_dream.html.erb
<li>
  <% unless dream.spooky?  %>
    <%= link_to dream.title, dream_url(dream)%>
  <% else %>
    👻
  <% end %>
</li>

week5/w5d1/dreams_app/app/views/dreams/_form.html.erb
<% if @dream.persisted? %>
  <% method = "patch" %>
  <% attributes = @dream.attributes %>
  <% action = dream_url(@dream) %>
<% else %>
  <% method = "post" %>
  <% attributes = {} %>
  <% action = dreams_url %>
<% end %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label for="">Title
    <input type="password" name="dream[title]" value="<%= attributes["title"] %>">
  </label>
  <label for="">Content
    <input type="password" name="dream[content]" value="<%= attributes["content"] %>">
  </label>
  <label for="">Completeness
    <input type="password" name="dream[completeness]" value="<%= attributes["completeness"] %>">
  </label>
  <label for="">Spooky?
    <input type="radio" name="dream[spooky]" value="true" <%= "checked" if @dream.persisted? && @dream.spooky? %>>
  </label>
  <label for="">non_spooky
    <input type="radio" name="dream[spooky]" value="false" <%= "checked" if @dream.persisted? && !@dream.spooky? %>>
  </label>
  <br>

  <input type="submit" value="Dream Builder">
</form>

week5/w5d1/dreams_app/app/views/dreams/edit.html.erb
<h1>Dreams#edit</h1>

<%= render "form" %>

week5/w5d1/dreams_app/app/views/dreams/index.html.erb
<h1>Dreams#index</h1>

<h3>asdfasdf</h3>
<ul>
  <%= render @dreams %>
</ul>

<%= link_to "Google", "http://www.google.com" %>

<%= link_to "Dream Builder", new_dream_url %>

week5/w5d1/dreams_app/app/views/dreams/new.html.erb
<h1>Dreams#new</h1>

<%= render "form" %>

week5/w5d1/dreams_app/app/views/dreams/show.html.erb
<h1>Dreams#show</h1>

<%= @dream.title %> |
<%= @dream.content %> |
<%= @dream.completeness %> |
Spooky?: <%= @dream.spooky %>n

<br>

<ul>
<% @dream.comments.each do |comment| %>
  <li><% if comment.spooky %>
      👻
    <% else %>
      <%= comment.body %>
    <% end %></li>
<% end %>
</ul>

<h6>Add Dream Comment</h6>

<form class="" action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[commentable_type]" value="Dream">
  <input type="hidden" name="comment[commentable_id]" value="<%= @dream.id %>">

  <br>
  <label for="">body
    <input type="password" name="comment[body]">
  </label>
  <br>
  <label for="">spooky
    <input type="radio" name="comment[spooky]" value="true" >
  </label>
  <label for="">non_spooky
    <input type="radio" name="comment[spooky]" value="false">
  </label>
  <br>

<input type="submit" value="Add Dream Comment">

</form>

week5/w5d1/dreams_app/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label for="Username">Username
    <input type="text" name="user[username]">
  </label>
  <label for="Password">Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Hello">
</form>

week5/w5d1/dreams_app/app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h3>My Spooky and Non-Spooky Dreams :( 💑 😱💀💩</h3>
<ul>
  <%= render partial: 'dreams/dream', collection: @user.dreams %>
</ul>

<p>💑 😱💀💩</p>

<br>

<ul>
<% @user.comments.each do |comment| %>
  <li><% if comment.spooky %>
      👻
    <% else %>
      <%= comment.body %>
    <% end %></li>
<% end %>
</ul>

<h6>Add Comment</h6>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[commentable_type]" value="User">
  <input type="hidden" name="comment[commentable_id]" value="<%= @user.id %>">

  <br>
  <label for="">body
    <input type="Password" name="comment[body]">
  </label>
  <br>
  <label for="">spooky
    <input type="radio" name="comment[spooky]" value="true" >
  </label>
  <label for="">non_spooky
    <input type="radio" name="comment[spooky]" value="false">
  </label>
  <br>

<input type="submit" value="Dream Comment">

</form>